CREATE PROCEDURE PAACTIVA()
BEGIN
    SET @@TRIGGER_DISABLED = 1;
    INSERT INTO RENTA (NUMERO, CI, NIT, FECHA, COSTOCF, DESCUENTO) VALUES (1, 1, 1, NOW(), 100, 0);
    SET @@TRIGGER_DISABLED = 0;
END;
