CREATE FUNCTION FUN_EJEMPLO7(mes INT, anio INT)
RETURNS DECIMAL(10,2)
BEGIN
    DECLARE costoMinimo DECIMAL(10,2);
    SELECT MIN(COSTOTOTAL) INTO costoMinimo FROM COMPRA
    WHERE YEAR(FECHASOL) = anio AND MONTH(FECHASOL) = mes;
    RETURN costoMinimo;
END