CREATE FUNCTION FUN_EJEMPLO9(nombreEmpresa VARCHAR(100), descripcionArticulo VARCHAR(100))
RETURNS DECIMAL(10,2)
BEGIN
    DECLARE cantidad DECIMAL(10,2);
    SELECT AVG(CANTIDAD) INTO cantidad FROM COMPRA c INNER JOIN ARTICULO a ON c.CODART = a.CODART 
    INNER JOIN EMPRESA e ON c.NITEMP = e.NITEMP 
    WHERE e.NOMBREEMP = nombreEmpresa AND a.DESCRIPCION = descripcionArticulo;
    RETURN cantidad;
END