create database P07;
use P07;

-- Crear tabla EMPRESA
CREATE TABLE EMPRESA (
  NITEMP INT PRIMARY KEY,
  NOMBREEMP VARCHAR(100) NOT NULL,
  TELEFONOEMP VARCHAR(20) NOT NULL,
  DIRECCIONEMP VARCHAR(100) NOT NULL
);

-- Crear tabla SUCURSAL
CREATE TABLE SUCURSAL (
  NITEMP INT NOT NULL,
  CIUDAD VARCHAR(100) NOT NULL,
  DIRECCIONSUC VARCHAR(100) NOT NULL,
  TELEFONOSUC VARCHAR(20) NOT NULL,
  PRIMARY KEY (NITEMP, CIUDAD),
  FOREIGN KEY (NITEMP) REFERENCES EMPRESA(NITEMP)
);

-- Crear tabla PERSONAL
CREATE TABLE PERSONAL (
  ITEMPER INT PRIMARY KEY,
  NOMBREPER VARCHAR(100) NOT NULL,
  EDAD INT NOT NULL,
  SEXO VARCHAR(1) NOT NULL,
  FECHAINGRESO DATE NOT NULL,
  NITEMP INT NOT NULL,
  FOREIGN KEY (NITEMP) REFERENCES EMPRESA(NITEMP)
);

-- Crear tabla ARTICULO
CREATE TABLE ARTICULO (
  CODART INT PRIMARY KEY,
  DESCRIPCION VARCHAR(100) NOT NULL,
  UNIDADMEDIDA VARCHAR(10) NOT NULL,
  PRECIO DECIMAL(10,2) NOT NULL
);

-- Crear tabla SOLICITUD
CREATE TABLE SOLICITUD (
  NUMSOL INT PRIMARY KEY,
  FECHASOL DATE NOT NULL,
  CANTIDADSOL INT NOT NULL,
  ST VARCHAR(1) NOT NULL,
  ITEMPER INT NOT NULL,
  CODART INT NOT NULL,
  FOREIGN KEY (ITEMPER) REFERENCES PERSONAL(ITEMPER),
  FOREIGN KEY (CODART) REFERENCES ARTICULO(CODART)
);

-- Crear tabla COMPRA
CREATE TABLE COMPRA (
  CODART INT NOT NULL,
  NITEMP INT NOT NULL,
  CANTIDAD INT NOT NULL,
  COSTOTOTAL DECIMAL(10,2) NOT NULL,
  NUMSOL INT NOT NULL,
  PRIMARY KEY (CODART, NITEMP, NUMSOL),
  FOREIGN KEY (CODART) REFERENCES ARTICULO(CODART),
  FOREIGN KEY (NITEMP) REFERENCES EMPRESA(NITEMP),
  FOREIGN KEY (NUMSOL) REFERENCES SOLICITUD(NUMSOL)
);